<a href="https://colab.research.google.com/github/ykitaguchi77/CongenitalGlaucoma_AI_project/blob/main/DataSplit(stratified_one_subject_leave_out)1.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Data_split for one-subject-leave-out stratified 5-fold crossvalidation**

In [ ]:
"""
Leave one subject out cross validation + 5-fold stratified cross validation

・1症例を抜き出し、その症例のすべての画像をテスト画像とする
・残りの症例の内斜視、外斜視、斜視なし群を、同じ症例が群をまたがないように5分割する。
・5分割したデータセットのうち4つをtraining、1つをvalidationとして用いてトレーニングを行い、抜き出した1症例のそれぞれの画像のおける正解率を算出する。これを5回繰り返してcross validationとする。

"""

In [15]:
def make_path_list(dir):
    path_list =  [file for file in glob.glob(dir+"/*") if os.path.isfile(file) == True ]
    return path_list

gla_ortho_path = r"F:\先天性緑内障\データ引継ぎ\children_d"
pathlist = make_path_list(gla_ortho_path)
print(pathlist)



['F:\\先天性緑内障\\データ引継ぎ\\children_d\\1546_2.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\1546_6.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\1546_7.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\1546_9.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\1962_1.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\2004_12.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\2004_28.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\2004_33.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\2004_34.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\2761_10.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\2761_2.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\2761_3.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\2761_9.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\3422_1.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\3422_2.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\4377_19.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\4377_20.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\4407_3.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\4407_1.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\4407_2.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\4849_24.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\chil

In [59]:
import codecs
import pandas as pd
import os
import numpy as np
import shutil
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.model_selection import StratifiedGroupKFold
import pandas as pd
from PIL import Image
import tempfile
import time
import glob
import itertools

pd.set_option('display.max_rows', 500)

gla_ortho_path = r"F:\先天性緑内障\データ引継ぎ\children_d"
gla_eso_path = r"F:\先天性緑内障\データ引継ぎ\children_d__内斜視"
gla_exo_path = r"F:\先天性緑内障\データ引継ぎ\children_d__外斜視"
cont_ortho_path = r"F:\先天性緑内障\データ引継ぎ\children_control"
cont_eso_path = r"F:\先天性緑内障\データ引継ぎ\children_control__内斜視\内斜視かぶりなし"
cont_exo_path = r"F:\先天性緑内障\データ引継ぎ\children_control__外斜視\外斜視かぶりなし"


def make_path_list(dir):
    path_list =  [file for file in glob.glob(dir+"/*") if os.path.isfile(file) == True ]
    return path_list

def extract_class(path_list, className):
    class_list = list(itertools.repeat(className,len(path_list)))
    return class_list

def extract_ids(path_list):
    id_list = [os.path.basename(name).split("_")[0] for name in path_list]
    return(id_list)


gla_ortho_path_list = make_path_list(gla_ortho_path)
gla_eso_path_list = make_path_list(gla_eso_path)
gla_exo_path_list = make_path_list(gla_exo_path)
cont_ortho_path_list = make_path_list(cont_ortho_path)
cont_eso_path_list = make_path_list(cont_eso_path)
cont_exo_path_list = make_path_list(cont_exo_path)

#それぞれの項目（path, classes, ID）をリスト化
gla_dataset_path = gla_ortho_path_list + gla_eso_path_list + gla_exo_path_list
gla_classes = extract_class(gla_ortho_path_list, "ortho") + extract_class(gla_eso_path_list, "eso") + extract_class(gla_exo_path_list, "exo")
gla_id = extract_ids(gla_ortho_path_list) + extract_ids(gla_eso_path_list) + extract_ids(gla_exo_path_list)
cont_dataset_path = cont_ortho_path_list + cont_eso_path_list + cont_exo_path_list
cont_classes = extract_class(cont_ortho_path_list, "ortho") + extract_class(cont_eso_path_list, "eso") + extract_class(cont_exo_path_list, "exo")
cont_id = extract_ids(cont_ortho_path_list) + extract_ids(cont_eso_path_list) + extract_ids(cont_exo_path_list)

#convert to Numpy
gla_dataset_path = np.array(gla_dataset_path)
gla_classes = np.array(gla_classes)
gla_id = np.array(gla_id)
cont_dataset_path = np.array(cont_dataset_path)
cont_classes = np.array(cont_classes)
cont_id = np.array(cont_id)

print(len(gla_dataset_path))

204


In [ ]:
"""
------test_dataset[0]
  |
  |---train_dataset_gla[0]----0
  |                        |--1
  |                        |--2
  |                        |--3
  |                        |--4
  |---train_dataset_cont[0]----0
  |                         |--1
  |                         |--2
  |                         |--3
  |                         |--4
  |---val_dataset_gla[0]----0
  |                      |--1
  |                      |--2
  |                      |--3
  |                      |--4
  |---val_dataset_cont[0]----0
  |                       |--1
  |                       |--2
  |                       |--3
  |                       |--4
  |---test_dataset[1]
  ...

"""

In [60]:
train_dataset_gla, val_dataset_gla,train_dataset_cont, val_dataset_cont, test_dataset = [], [], [], [], []

#まずglaのデータセットから1人分を抜き出す（LeaveOneGroupOut)
logo = LeaveOneGroupOut()
logo.get_n_splits(gla_dataset_path, gla_classes, gla_id)
logo.get_n_splits(groups=gla_id)  # 'groups' is always required

k=0
for remain_index, test_index in logo.split(gla_dataset_path, gla_classes, gla_id):
    gla_dataset_path_remain, gla_dataset_path_test = gla_dataset_path[remain_index], gla_dataset_path[test_index]
    gla_classes_remain, gla_classes_test = gla_classes[remain_index], gla_classes[test_index]
    gla_id_remain, gla_id_test = gla_id[remain_index], gla_id[test_index]
    #print(gla_dataset_path, gla_dataset_path_test, gla_id_train, gla_id_test)
    #print("test: "+gla_id_test[0])
    #print("TRAIN:", remain_index, "TEST:", test_index)
    #print(gla_dataset_path_test)
    test_dataset.append(gla_dataset_path_test.tolist())

    #抜き出した残りのglaについてStratified group 5-foldをかける
    cv = StratifiedGroupKFold(n_splits=5)
    m=0 
    train_miniset, val_miniset =  [0 for i in range(0, 5)], [0 for i in range(0, 5)]
    for train_idxs, val_idxs in cv.split(gla_dataset_path_remain, gla_classes_remain, gla_id_remain):
        #print("TRAIN:", gla_classes_remain[train_idxs])
        #print("      ", gla_id_remain[train_idxs])
        #print("      ", gla_dataset_path_remain[train_idxs])
        #print(" TEST:", gla_classes_remain[val_idxs])
        #print("      ", gla_id_remain[val_idxs])
        #print("      ", gla_dataset_path_remain[val_idxs])
        train_miniset[m] = gla_dataset_path_remain[train_idxs].tolist()
        val_miniset[m] = gla_dataset_path_remain[val_idxs].tolist()
        m+=1
    train_dataset_gla.append(train_miniset)
    val_dataset_gla.append(val_miniset)

    #controlについてStratified group 5-foldをかける
    m=0 
    train_miniset, val_miniset =  [0 for i in range(0, 5)], [0 for i in range(0, 5)]
    for train_idxs, val_idxs in cv.split(cont_dataset_path, cont_classes, cont_id):
        #print("TRAIN:", cont_classes[train_idxs])
        #print("      ", cont_id[train_idxs])
        #print("      ", cont_dataset_path[train_idxs])
        #print(" TEST:", cont_classes[val_idxs])
        #print("      ", cont_id[val_idxs])
        #print("      ", cont_dataset_path[val_idxs])
        train_miniset[m] = cont_dataset_path[train_idxs].tolist()
        val_miniset[m] = cont_dataset_path[val_idxs].tolist()
        m+=1
    train_dataset_cont.append(train_miniset)
    val_dataset_cont.append(val_miniset)

        
print(len(train_dataset_gla))    
print(len(val_dataset_gla))
print(val_dataset_gla)
#print(len(train_dataset_cont))    
#print(len(val_dataset_cont))
#print(len(test_dataset))




30
30
[[['F:\\先天性緑内障\\データ引継ぎ\\children_d\\2761_10.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\2761_2.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\2761_3.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\2761_9.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\4377_19.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\4377_20.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\4849_24.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\4849_25.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\4849_3.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\4849_43.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\4849_46.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\4849_48.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\4849_5.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\4849_50.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\8246_1.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\8500_16.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\8500_17.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\8500_18.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\8500_2.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d\\8500_21.jpg', 'F:\\先天性緑内障\\データ引継ぎ\\children_d__内斜視\\2761_4.jpg', 'F:\\先天

In [ ]:





"""
os.makedirs(os.path.join(dname, "train/gla"))
os.makedirs(os.path.join(dname, "train/cont"))
os.makedirs(os.path.join(dname, "val/gla"))
os.makedirs(os.path.join(dname, "val/cont"))
os.makedirs(os.path.join(dname, "test"))
"""
"""
#保存先フォルダを作成
if os.path.exists(dst_path):
    pass
    #shutil.rmtree(dst_path)
os.makedirs(dst_path, exist_ok=True)
"""

#まずglaのデータセットから1人分を抜き出す（LeaveOneGroupOut)
logo = LeaveOneGroupOut()
logo.get_n_splits(gla_dataset_path, gla_classes, gla_id)
logo.get_n_splits(groups=gla_id)  # 'groups' is always required

for remain_index, test_index in logo.split(gla_dataset_path, gla_classes, gla_id):
    gla_dataset_path_remain, gla_dataset_path_test = gla_dataset_path[remain_index], gla_dataset_path[test_index]
    gla_classes_remain, gla_classes_test = gla_classes[remain_index], gla_classes[test_index]
    gla_id_remain, gla_id_test = gla_id[remain_index], gla_id[test_index]
    #print(gla_dataset_path, gla_dataset_path_test, gla_id_train, gla_id_test)
    print("test: "+gla_id_test[0])
    print("TRAIN:", remain_index, "TEST:", test_index)
    print(gla_dataset_path_test)
    #print(gla_id_train)


    """
    #抜き出したデータのIDでフォルダを作成
    os.makedirs(os.path.join(dst_path, gla_id_test[0]), exist_ok=True)
    os.chdir(os.path.join(dst_path, gla_id_test[0]))
    for i in range(5):
        for j in ["train", "val"]:
            for k in ["gla", "cont"]:
                os.makedirs(os.path.join(str(i), j, k), exist_ok=True)
    os.makedirs("test", exist_ok=True) #判定のための画像
    print(os.listdir(dst_path))
    print("")
    """
    
    """
    #testフォルダにコピー
    for file in gla_dataset_path_test:
        #print(file)
        shutil.copyfile(file, "./test/"+ os.path.basename(file))
    

    #抜き出した残りのglaについてStratified group 5-foldをかける
    cv = StratifiedGroupKFold(n_splits=5)
    m=0
    for train_idxs, val_idxs in cv.split(gla_dataset_path_remain, gla_classes_remain, gla_id_remain):
        #print("TRAIN:", gla_classes_remain[train_idxs])
        #print("      ", gla_id_remain[train_idxs])
        #print("      ", gla_dataset_path_remain[train_idxs])
        #print(" TEST:", gla_classes_remain[val_idxs])
        #print("      ", gla_id_remain[val_idxs])
        #print("      ", gla_dataset_path_remain[val_idxs])
        for idx in train_idxs:
            #print(gla_dataset_path_remain[idx])
            #print("./"+str(m)+"/train/gla/"+os.path.basename(gla_dataset_path_remain[idx]))

            #250pxにリサイズして保存
            resize_and_save_img(gla_dataset_path_remain[idx], "./"+str(m)+"/train/gla/"+os.path.basename(gla_dataset_path_remain[idx]))
            #shutil.copyfile(gla_dataset_path_remain[idx], "./"+str(m)+"/train/gla/"+os.path.basename(gla_dataset_path_remain[idx]))
        for idx in val_idxs:
            resize_and_save_img(gla_dataset_path_remain[idx], "./"+str(m)+"/val/gla/"+os.path.basename(gla_dataset_path_remain[idx]))
            #shutil.copyfile(gla_dataset_path_remain[idx], "./"+str(m)+"/val/gla/"+os.path.basename(gla_dataset_path_remain[idx]))
        print("Making "+str(m+1)+"/5 crossvalidation folders for glaucoma dataset!")
        m+=1

    #cont全体についてもStratified group-foldをかける
    m=0
    for train_idxs, val_idxs in cv.split(cont_dataset_path, cont_classes, cont_id):
        #print("TRAIN:", cont_classes[train_idxs])
        #print("      ", cont_id[train_idxs])
        #print("      ", cont_dataset_path[train_idxs])
        #print(" TEST:", cont_classes[val_idxs])
        #print("      ", cont_id[val_idxs])
        #print("      ", cont_dataset_path[val_idxs])
        for idx in train_idxs:
            #print(cont_dataset_path[idx])
            #print("./"+str(m)+"/train/cont/"+os.path.basename(cont_dataset_path_remain[idx]))
            
            resize_and_save_img(cont_dataset_path[idx], "./"+str(m)+"/train/cont/"+os.path.basename(cont_dataset_path[idx]))
            #shutil.copyfile(cont_dataset_path[idx], "./"+str(m)+"/train/cont/"+os.path.basename(cont_dataset_path[idx]))
        for idx in val_idxs:
            resize_and_save_img(cont_dataset_path[idx], "./"+str(m)+"/val/cont/"+os.path.basename(cont_dataset_path[idx]))
            #shutil.copyfile(cont_dataset_path[idx], "./"+str(m)+"/val/cont/"+os.path.basename(cont_dataset_path[idx]))
        
        print("Making "+str(m+1)+"/5 crossvalidation folders for control dataset!")
        m+=1


#Contのデータセットでも同じことをやる
#まずcontのデータセットから1人分を抜き出す（LeaveOneGroupOut)
logo = LeaveOneGroupOut()
logo.get_n_splits(cont_dataset_path, cont_classes, cont_id)
logo.get_n_splits(groups=cont_id)  # 'groups' is always required

for remain_index, test_index in logo.split(cont_dataset_path, cont_classes, cont_id):
    #print("TRAIN:", train_index, "TEST:", test_index)
    cont_dataset_path_remain, cont_dataset_path_test = cont_dataset_path[remain_index], cont_dataset_path[test_index]
    cont_classes_remain, cont_classes_test = cont_classes[remain_index], cont_classes[test_index]
    cont_id_remain, cont_id_test = cont_id[remain_index], cont_id[test_index]
    #print(cont_dataset_path, cont_dataset_path_test, cont_id_train, cont_id_test)
    print(cont_id_test)
    #print(cont_id_train)

    #抜き出したデータのIDでフォルダを作成
    os.makedirs(os.path.join(dst_path, cont_id_test[0]), exist_ok=True)
    os.chdir(os.path.join(dst_path, cont_id_test[0]))
    for i in range(5):
        for j in ["train", "val"]:
            for k in ["gla", "cont"]:
                os.makedirs(os.path.join(str(i), j, k), exist_ok=True)
    os.makedirs("test", exist_ok=True) #判定のための画像
    
    
    #testフォルダにコピー
    for file in cont_dataset_path_test:
        #print(file)
        shutil.copyfile(file, "./test/"+ os.path.basename(file))
    

    #抜き出した残りのcontについてStratified group 5-foldをかける
    cv = StratifiedGroupKFold(n_splits=5)
    m=0
    for train_idxs, val_idxs in cv.split(cont_dataset_path_remain, cont_classes_remain, cont_id_remain):
        #print("TRAIN:", cont_classes_remain[train_idxs])
        #print("      ", cont_id_remain[train_idxs])
        #print("      ", cont_dataset_path_remain[train_idxs])
        #print(" TEST:", cont_classes_remain[val_idxs])
        #print("      ", cont_id_remain[val_idxs])
        #print("      ", cont_dataset_path_remain[val_idxs])
        for idx in train_idxs:
            #print(cont_dataset_path_remain[idx])
            #print("./"+str(m)+"/train/cont/"+os.path.basename(cont_dataset_path_remain[idx]))
            
            resize_and_save_img(cont_dataset_path_remain[idx], "./"+str(m)+"/train/cont/"+os.path.basename(cont_dataset_path_remain[idx]))
            #shutil.copyfile(cont_dataset_path_remain[idx], "./"+str(m)+"/train/cont/"+os.path.basename(cont_dataset_path_remain[idx]))
        for idx in val_idxs:
            resize_and_save_img(cont_dataset_path_remain[idx], "./"+str(m)+"/val/cont/"+os.path.basename(cont_dataset_path_remain[idx]))
            #shutil.copyfile(cont_dataset_path_remain[idx], "./"+str(m)+"/val/cont/"+os.path.basename(cont_dataset_path_remain[idx]))
        
        print("Making "+str(m+1)+"/5 crossvalidation folders for control dataset!")
        m+=1

    #gla全体についてもStratified group-foldをかける
    m=0
    for train_idxs, val_idxs in cv.split(gla_dataset_path, gla_classes, gla_id):
        #print("TRAIN:", gla_classes[train_idxs])
        #print("      ", gla_id[train_idxs])
        #print("      ", gla_dataset_path[train_idxs])
        #print(" TEST:", gla_classes[val_idxs])
        #print("      ", gla_id[val_idxs])
        #print("      ", gla_dataset_path[val_idxs])
        for idx in train_idxs:
            #print(gla_dataset_path[idx])
            #print("./"+str(m)+"/train/gla/"+os.path.basename(gla_dataset_path_remain[idx]))
            
            resize_and_save_img(gla_dataset_path[idx], "./"+str(m)+"/train/gla/"+os.path.basename(gla_dataset_path[idx]))
            #shutil.copyfile(gla_dataset_path[idx], "./"+str(m)+"/train/gla/"+os.path.basename(gla_dataset_path[idx]))
        for idx in val_idxs:
            resize_and_save_img(gla_dataset_path[idx], "./"+str(m)+"/val/gla/"+os.path.basename(gla_dataset_path[idx]))
            #shutil.copyfile(gla_dataset_path[idx], "./"+str(m)+"/val/gla/"+os.path.basename(gla_dataset_path[idx]))
        
        print("Making "+str(m+1)+"/5 crossvalidation folders for glaucoma dataset!")
        m+=1
    """

In [ ]:
"""
gla_dataset_path
gla_classes(ortho, eso, exo)
gla_id
cont_dataset_path
cont_classes(ortho, eso, exo)
cont_id

gla_dataset_pathからidが同じグループを1つ抜き出し、テスト画像とする(gla_dataset_test, gla_dataset_remain)
gla_dataset_remainに対してStratified group 5-foldをかける
cont_datasetに対してStratified group 5-foldをかける
5-foldを同期させて、datasetを作成する（train_gla, train_cont, val_gla, val_cont)
このデータセットでdeep learningする
テスト画像を判定し、正解率を調べる

cont_dataset_pathに関しても同様の処理をして正解率を調べる
"""

class SimpleImageDataset(Dataset):
    def __init__(self, data_path_list, data_classes_list, transforms):
        self.transform = transform
        self.data_paths = data_path_list
        self.target = data_class_list
        self.datanum = lepath_list)

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, idx):
        image_path = self.data_paths[idx]
        pilr_image = Image.open(image_path).convert("RGB")
        tensor_image = self.transform(pilr_image)
        target = torch.tensor([self.target[idx]])      
        return tensor_image, target



#それぞれの項目（path, classes, ID）をリスト化
gla_dataset_path = df_gla_all.iloc[:,2].transpose().values
gla_classes = df_gla_all.iloc[:,0].transpose().values
gla_id = df_gla_all.iloc[:,1].transpose().values
cont_dataset_path = df_cont_all.iloc[:,2].transpose().values
cont_classes = df_cont_all.iloc[:,0].transpose().values
cont_id = df_cont_all.iloc[:,1].transpose().values

#OneSubjectLeaveOutによる患者抜き出し
for remain_index, test_index in logo.split(gla_dataset_path, gla_classes, gla_id):
    #print("TRAIN:", train_index, "TEST:", test_index)
    gla_dataset_path_remain, gla_dataset_path_test = gla_dataset_path[remain_index], gla_dataset_path[test_index]
    gla_classes_remain, gla_classes_test = gla_classes[remain_index], gla_classes[test_index]
    gla_id_remain, gla_id_test = gla_id[remain_index], gla_id[test_index]
    print(gla_id_test)

    test = 

    #抜き出したデータのIDでフォルダを作成
    os.makedirs(os.path.join(dst_path, gla_id_test[0]), exist_ok=True)
    os.chdir(os.path.join(dst_path, gla_id_test[0]))
    for i in range(5):
        for j in ["train", "val"]:
            for k in ["gla", "cont"]:
                os.makedirs(os.path.join(str(i), j, k), exist_ok=True)
    os.makedirs("test", exist_ok=True) #判定のための画像
    
    #testフォルダにコピー
    for file in gla_dataset_path_test:
        #print(file)
        shutil.copyfile(file, "./test/"+ os.path.basename(file))
    

In [ ]:
# one group leave out 見本
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.LeaveOneGroupOut.html#sklearn.model_selection.LeaveOneGroupOut
# 今回のケースでは、groupがIDに該当
import numpy as np
from sklearn.model_selection import LeaveOneGroupOut
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
y = np.array([1, 2, 1, 2, 1, 1])
groups = np.array([1, 1, 2, 3, 3, 4])
logo = LeaveOneGroupOut()
logo.get_n_splits(X, y, groups)
logo.get_n_splits(groups=groups)  # 'groups' is always required
print(logo)
LeaveOneGroupOut()
for train_index, test_index in logo.split(X, y, groups):
     print("TRAIN:", train_index, "TEST:", test_index)
     X_train, X_test = X[train_index], X[test_index]
     y_train, y_test = y[train_index], y[test_index]
     print(X_train, X_test, y_train, y_test)

LeaveOneGroupOut()
TRAIN: [2 3 4 5] TEST: [0 1]
[[ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] [[1 2]
 [3 4]] [1 2 1 1] [1 2]
TRAIN: [0 1 3 4 5] TEST: [2]
[[ 1  2]
 [ 3  4]
 [ 7  8]
 [ 9 10]
 [11 12]] [[5 6]] [1 2 2 1 1] [1]
TRAIN: [0 1 2 5] TEST: [3 4]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [11 12]] [[ 7  8]
 [ 9 10]] [1 2 1 1] [2 1]
TRAIN: [0 1 2 3 4] TEST: [5]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] [[11 12]] [1 2 1 2 1] [1]


In [ ]:
# example of stratified group Kfold　見本
# 今回のケースでは、groupがID、yがclassesに該当
import numpy as np
from sklearn.model_selection import StratifiedGroupKFold
X = np.ones((17, 2))
y = np.array([0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])
groups = np.array([1, 1, 2, 2, 3, 3, 3, 4, 5, 5, 5, 5, 6, 6, 7, 8, 8])
cv = StratifiedGroupKFold(n_splits=3)

print(X)
print(y)
print(groups)

for train_idxs, test_idxs in cv.split(X, y, groups):
    print("TRAIN:", groups[train_idxs])
    print("      ", y[train_idxs])
    print(" TEST:", groups[test_idxs])
    print("      ", y[test_idxs])

In [ ]:
# one group leave out 
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.LeaveOneGroupOut.html#sklearn.model_selection.LeaveOneGroupOut
# 今回のケースでは、groupがIDに該当
import numpy as np
from sklearn.model_selection import LeaveOneGroupOut
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
y = np.array([1, 2, 1, 2, 1, 1])
groups = np.array([1, 1, 2, 3, 3, 4])
logo = LeaveOneGroupOut()
logo.get_n_splits(X, y, groups)
logo.get_n_splits(groups=groups)  # 'groups' is always required
print(logo)
LeaveOneGroupOut()
for train_index, test_index in logo.split(X, y, groups):
     print("TRAIN:", train_index, "TEST:", test_index)
     X_train, X_test = X[train_index], X[test_index]
     y_train, y_test = y[train_index], y[test_index]
     print(X_train, X_test, y_train, y_test)

LeaveOneGroupOut()
TRAIN: [2 3 4 5] TEST: [0 1]
[[ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] [[1 2]
 [3 4]] [1 2 1 1] [1 2]
TRAIN: [0 1 3 4 5] TEST: [2]
[[ 1  2]
 [ 3  4]
 [ 7  8]
 [ 9 10]
 [11 12]] [[5 6]] [1 2 2 1 1] [1]
TRAIN: [0 1 2 5] TEST: [3 4]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [11 12]] [[ 7  8]
 [ 9 10]] [1 2 1 1] [2 1]
TRAIN: [0 1 2 3 4] TEST: [5]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] [[11 12]] [1 2 1 2 1] [1]
